# Generated by Django 4.1.5 on 2023-04-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admin_details'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=20)),
                ('Service', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Slot', models.CharField(max_length=50)),
            ],
        ),
    ]
