# Generated by Django 4.1.5 on 2023-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='Token',
            field=models.IntegerField(default=1),
        ),
    ]
