# Generated by Django 4.1.5 on 2023-04-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booking_details_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_details',
            name='Username',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
