# Generated by Django 4.1.5 on 2023-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_details_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
