# Generated by Django 4.1.5 on 2023-05-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_booking_details_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_success', models.CharField(max_length=50)),
                ('booking_cancelled', models.CharField(max_length=50)),
            ],
        ),
    ]
