# Generated by Django 4.1.5 on 2023-05-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
