# Generated by Django 4.1.5 on 2023-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_booking_details_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel_notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_cancelled', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='success_notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_success', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='notification',
        ),
    ]
