# Generated by Django 4.1.5 on 2023-05-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cancel_notification_success_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_details_for_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=10)),
                ('Category', models.CharField(max_length=20)),
                ('Service', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Slot', models.CharField(max_length=50)),
                ('Token', models.IntegerField(default=1)),
            ],
        ),
    ]
