# Generated by Django 4.1.5 on 2023-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_booking_details_for_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
