# Generated by Django 4.1.5 on 2023-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_booking_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details_for_user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
