# Generated by Django 4.1.5 on 2023-05-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_booking_details_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_notification',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='success_notification',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
