# Generated by Django 4.1.5 on 2023-05-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_cancel_notification_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel_notification',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='success_notification',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
