# Generated by Django 4.1.5 on 2023-05-16 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_cancel_notification_time_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_notification',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='success_notification',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
