# Generated by Django 4.1.5 on 2023-05-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_cancel_notification_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Date',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='booking_details_for_user',
            name='Date',
            field=models.DateField(max_length=10),
        ),
    ]
