# Generated by Django 4.1.5 on 2023-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_booking_details_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_details',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking_details_for_user',
            name='Date',
            field=models.DateField(),
        ),
    ]
