# Generated by Django 4.1.5 on 2023-05-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='haircut_price_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kids', models.CharField(max_length=10)),
                ('Male', models.CharField(max_length=10)),
                ('Female', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='makeup_price_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kids', models.CharField(max_length=10)),
                ('Male', models.CharField(max_length=10)),
                ('Female', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='massage_price_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kids', models.CharField(max_length=10)),
                ('Male', models.CharField(max_length=10)),
                ('Female', models.CharField(max_length=10)),
            ],
        ),
    ]
